In [17]:
#importing important libraries
import numpy as ns
import pandas as pd  
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
#importing train,test,split,logisticregression and standardScaler from sklearn
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, roc_auc_score,
    confusion_matrix, roc_curve, classification_report
)

In [19]:
#loading dataset
df = pd.read_csv('../../cleaned_data/titanic_cleaned.csv')

In [20]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500       0.0
1         1       1    0  38.0      1      0  71.2833       1.0
2         1       3    0  26.0      0      0   7.9250       0.0
3         1       1    0  35.0      1      0  53.1000       0.0
4         0       3    1  35.0      0      0   8.0500       0.0

FEATURE ENGINEERING

In [ ]:
df_fe = df.copy()

#Feature_1 Family Size
df_fe['Family_Size'] = df_fe['Parch'] + df_fe['SibSp'] + 1

#herer i added columns parch and sibsp for counting Family_Size

In [22]:
#Feature is_alone
df_fe['is_alone'] = (df_fe['Family_Size'] == 1).astype(int)

In [23]:
#Age_x_Pclass 
df_fe['Age_x_Pclass'] = df_fe['Age'] * df_fe['Pclass']

#multiplying age * Pclass to get age by pclass

In [24]:
#Fare per Person

df_fe['FarePerPerson'] = df_fe['Fare'] / df_fe['Family_Size']
#dividing fare/family_size to get fare by each person

In [25]:
# Feature 5: Age Group
df_fe['AgeGroup'] = pd.cut(
    df_fe['Age'],
    bins=[0, 12, 18, 35, 60, 100],
    labels=[0, 1, 2, 3, 4]  # child, teen, young adult, adult, senior
).astype(int)


print('new features created!')
print('New columns:', ['Family_Size', 'is_alone', 'Age_x_Pclass', 'FarePerPerson', 'AgeGroup'])

new features created!
New columns: ['Family_Size', 'is_alone', 'Age_x_Pclass', 'FarePerPerson', 'AgeGroup']

In [27]:
df = df_fe 

df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Family_Size,is_alone,Age_x_Pclass,FarePerPerson,AgeGroup
0,0,3,1,22.0,1,0,7.2500,0.0,2,0,66.0,3.62500,2
1,1,1,0,38.0,1,0,71.2833,1.0,2,0,38.0,35.64165,3
2,1,3,0,26.0,0,0,7.9250,0.0,1,1,78.0,7.92500,2
3,1,1,0,35.0,1,0,53.1000,0.0,2,0,35.0,26.55000,2
4,0,3,1,35.0,0,0,8.0500,0.0,1,1,105.0,8.05000,2

VISUALIZING NEW FEATURES